# 服务期类型， 可选值有
# grpc： 启动一个grpc服务
# grpc-gateway: 启动一个grpc服务器 + http反向代理服务器
# gin：基于gin框架启动一个http服务器
# 服务器模式选择
# - 应用内部调用选择 grpc
# - 如果由外部服务调用选择 grpc-gateway
# - 学习gin框架是选择gin
server-mode: grpc-gateway
#JWT 签发秘钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

# 日志配置
log:
  # 是否开启caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-caller: false
  # 是否禁止在panic及以上级别打印栈信息，可以减少无用日志的输出
  disable-stacktrace: false
  # 指定日志级别，可选 debug， info， warn， error， dpanic。 panic， fatal
  level: info
  # 指定日志显示格式，可选值：console, json
  # 生产环境建议设置为 json
  format: json
  # 指定日志输出位置，多个输出，用`逗号 + 空格` 分开。stdout：标准输出
  output-paths: [/tmp/miniblog.log, stdout]
